language: ruby
before_install:
   - gem install bundler -v 1.10
script: bundle exec rake --verbose --trace
bundler_args: --without development
matrix:
  allow_failures:
      - rvm: ruby-head
rvm:
  - jruby
  - rbx-2
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - ruby-head

