language: ruby
before_install:
   - gem install bundler -v 1.10
script: bundle exec rake --verbose --trace
bundler_args: --without development
matrix:
  allow_failures:
      - rvm: ruby-head
      - rvm: rbx-2
rvm:
  - jruby
  - rbx-2
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.3
  - 2.4.0
  - ruby-head

